apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers: []
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true,Refresh=hard
spec:
  destination:
    namespace: app-nginx
    server: https://kubernetes.default.svc
  source:
    path: infra/kube
    repoURL: https://github.com/barnabe-josepavel/test-argo-cd
    targetRevision: prod
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
